trigger:
  - devops

pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: "clouddevops-portfolio"
  dockerId: "lahbariismail1991"

stages:
  - stage: BuildAndPush
    displayName: "Build and Push to Docker Hub"
    jobs:
      - job: DockerPush
        displayName: "Build & Push Docker Image"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: "Build and Push Docker Image"
            inputs:
              containerRegistry: "dockerhub-connection" # Must match service connection name
              repository: "$(dockerId)/$(imageName)"
              command: buildAndPush
              Dockerfile: "Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              tags: |
                latest

          - script: echo "✅ Docker image built and pushed to Docker Hub."
            displayName: "Log Success"
