trigger:
  - devops

pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: "clouddevops-portfolio"
  dockerId: "lahbariismail1991"

stages:
  - stage: BuildAndPush
    displayName: "Build and Push to Docker Hub"
    jobs:
      - job: DockerPush
        displayName: "Build & Push Docker Image"
        steps:
          - checkout: self

          - task: Docker@2
            displayName: "Build and Push Docker Image"
            inputs:
              containerRegistry: "dockerhub-connection" # Must match service connection name
              repository: "$(dockerId)/$(imageName)"
              command: buildAndPush
              Dockerfile: "Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              tags: |
                latest

          - script: npm audit --audit-level=high
            displayName: "Audit Node.js dependencies"

          - script: |
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
              ./trivy image $(dockerId)/$(imageName):latest --exit-code 1 --severity HIGH,CRITICAL
            displayName: "Scan Docker image with Trivy"

          - script: echo "✅ Docker image built and pushed to Docker Hub."
            displayName: "Log Success"
