name: Build, Scan, and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Audit Node.js dependencies
        run: npm audit --audit-level=high

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: lahbariismail1991/clouddevops-portfolio:latest
          no-cache: true

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: lahbariismail1991/clouddevops-portfolio:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          skip-files: /usr/local/lib/node_modules

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lahbariismail1991/clouddevops-portfolio:latest
